version: "3"
services:
  reverseproxy:
    image: reverseproxy
    ports:
      - "8080:8080"
    depends_on:
      - backend_user
      - backend_feed
    networks:
      - udagram
  backend_user:
    image: udagram-api-user
    environment:
      - POSTGRES_USERNAME=udagram
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=udagram
      - POSTGRES_HOST=localhost
      - AWS_REGION=us-east-1
      - AWS_PROFILE=default
      - AWS_BUCKET=udagram-bucket-1234567
      - JWT_SECRET=hello
      - URL=http://localhost:8100
    depends_on:
      - udagram-db
    networks:
      - udagram
  backend_feed:
    image: udagram-api-feed
    environment:
      - POSTGRES_USERNAME=udagram
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=udagram
      - POSTGRES_HOST=localhost
      - AWS_REGION=us-east-1
      - AWS_PROFILE=default
      - AWS_BUCKET=udagram-bucket-1234567
      - JWT_SECRET=hello
      - URL=http://localhost:8100
    depends_on:
      - udagram-db
    networks:
      - udagram
  udagram-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=udagram
      - POSTGRES_DB=udagram
    networks:
      - udagram
networks:
  udagram:
    driver: bridge
